# Generated by Django 6.0.5 on 2026-05-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('producto', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('tienda', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo_tienda', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valido', models.BooleanField(default=True)),
                ('errores', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
